"""Removed nullable=false from expense

Revision ID: 088a057536dc
Revises: 58783508f530
Create Date: 2023-05-01 21:30:29.672942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088a057536dc'
down_revision = '58783508f530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
