"""Fix typo in Expense class

Revision ID: aaf2c83d87c0
Revises: 26d3a917e856
Create Date: 2023-04-26 15:22:13.915892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf2c83d87c0'
down_revision = '26d3a917e856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
