"""Correct typo in column names for Lease

Revision ID: f6069ac8b981
Revises: 088a057536dc
Create Date: 2023-05-03 14:04:25.870258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6069ac8b981'
down_revision = '088a057536dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_leases_tenent_id_tenants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_leases_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('tenent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenent_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_leases_tenant_id_tenants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_leases_tenent_id_tenants', 'tenants', ['tenent_id'], ['id'])
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
